const WIDTH = 320
const HALF_WIDTH = WIDTH / 2
const HEIGHT = 456
const SCORE_PANEL_HEIGHT = 30
const GAME_HEIGHT = 356
const PANEL_HEIGHT = HEIGHT - GAME_HEIGHT - SCORE_PANEL_HEIGHT
const TILE_SIZE = 32
const HALF_TILE_SIZE = TILE_SIZE / 2


export {
  WIDTH,
  HALF_WIDTH,
  GAME_HEIGHT,
  PANEL_HEIGHT,
  TILE_SIZE,
  HALF_TILE_SIZE,
  HEIGHT,
  SCORE_PANEL_HEIGHT
}
